// leave off @2x/@3x
const images = {
    avatarUrl: require('../Assets/Icons/Account_Circle.png'),
    logo: require('../Assets/Images/Hooda_Logo.png'),
    hoodaMerchantlogo: require('../Assets/Images/hooda_merchant_logo.svg'),
    moneyIcon: require('../Assets/Icons/Money.svg'),
    sendMoneyIcon: require('../Assets/Icons/Send_Money.svg'),
    boxIcon: require('../Assets/Icons/Box.svg'),
    cancelOrderIcon: require('../Assets/Icons/Cancel_Order.svg'),
    swapOrderIcon: require('../Assets/Icons/Swap_Order.svg'),
    seragamIcon: require('../Assets/Icons/Seragam.svg'),
    paymentIcon: require('../Assets/Icons/Payment.svg'),
    radioButtonCheckIcon: require('../Assets/Icons/Radio_Button_Checked.svg'),
    scheduleIcon: require('../Assets/Icons/Schedule.svg'),
    searchIcon: require('../Assets/Icons/Search.svg'),
    filterIcon: require('../Assets/Icons/Filter.svg'),
    hoodaFoodCircleImg: require('../Assets/Images/logo-hooda-food-circle.svg'),
    menu1Img: require('../Assets/Images/menu1.svg'),
    menu2Img: require('../Assets/Images/menu2.svg'),
    menu3Img: require('../Assets/Images/menu3.svg'),
    kurirImg: require('../Assets/Images/kurir.png'),
    ilustrationRegisterImg: require('../Assets/Images/Ilustrasi_Otorisasi.svg'),
    fastFoodExampleImg: require('../Assets/Images/fast-food-example.png'),
    avatarMaskur: require('../Assets/Icons/AvatarMaskur.png'),
    storeIcon: require('../Assets/Images/store.png'),
    foodcategoryIcon: require('../Assets/Images/foodcategory.png'),
    orderIcon: require('../Assets/Images/order.png'),
    excelIcon: require('../Assets/Icons/excel_icon.png'),
    pdfIcon: require('../Assets/Icons/pdf_icon.png'),
    todoImg: require('../Assets/Images/todo.png'),
    couponImg: require('../Assets/Images/coupon.png'),
    deliveryManImg: require('../Assets/Images/Delivery man.png'),
    discountImg: require('../Assets/Images/discount.png'),
    driverDiscountImg: require('../Assets/Images/driver discount.png'),
    rupiahImg: require('../Assets/Images/rupiah.png'),
    takeAwayImg: require('../Assets/Images/take-away.png'),
    barImg: require('../Assets/Images/bar.jpg'),
    ktpImg: require('../Assets/Images/ktp.jpg')
}

export default images